services:
  db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=share_it
      - POSTGRES_USER=${SHARE_IT_USER}
      - POSTGRES_PASSWORD=${SHARE_IT_PASSWORD}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
