spring:
  application.name: Share It
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/share_it
    username: ${SHARE_IT_USER}
    password: ${SHARE_IT_PASSWORD}
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql.init.mode: always
logging.level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO

