CREATE TABLE IF NOT EXISTS users
(
  id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name  VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  owner_id    BIGINT        NOT NULL REFERENCES users (id),
  name        VARCHAR(255)  NOT NULL,
  description VARCHAR(2000) NOT NULL,
  available   BOOLEAN       NOT NULL
);